[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "march clay release cousin secret usual nephew slow isolate rubber pass remove inform during loyal robot still dove rally chair net club thunder warrior"
